#+TITLE: Derp - a simple Slack bot
#+AUTHOR: dptd

* Installation
Derp uses [[https://github.com/dptd/jasa][JASA]] to communicate with the Slack API.

=git clone https://github.com/dptd/jasa=

=git clone https://github.com/dptd/derp=

=(ql:quickload :derp)=

* Usage
To create new derp use =(derp:spawn-derp)= function. This functions takes only one argument: derp-config. You can create config by calling =(derp:make-derp-config)=. Config is used to specify informations like derp displayed name, Slack API token etc.

Example below shows how to spawn a new derp.
#+BEGIN_SRC lisp
(setf derp
      (derp:spawn-derp
       (derp:make-derp-config :name "derp"
                              :icon ":robot_face:"
                              :token "YourSlackAPIToken"
                              :id "C01234567"
                              :channel "C01234567"
                              :commands '("cat" "ping" "help"))))
#+END_SRC

And here is how you can make your bot start derping...
#+BEGIN_SRC lisp
(derp:start-derping derp)
#+END_SRC

Check on your channel if derp is alive by writing: =@derp ping= Derp should response with =pong=.

* Supported commands

| command | description                                      |
|---------+--------------------------------------------------|
| cat     | displays random cat gif                          |
| dog     | displays random dog gif                          |
| +help   | displays available commands and the description+ |
| joke    | displays random Chuck Norris joke                |
| random  | picks one random person from the channel         |
| ping    | displays "pong" when alive                       |
| remove  | removes last derp's message                      |
| review  | picks two random people from the channel         |
